# ----
# Site

title: The Events Calendar Engineering Docs
url: "https://the-events-calendar.github.io"
baseurl: "/products-engineering"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: The Events Calendar knowledge base for Developers
author:
  name: The Events Calendar
  email:
  twitter: TheEventsCal

# -----
# Build

remote_theme: pmarsceill/just-the-docs

permalink: pretty

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "The Events Calendar":
    - "https://theeventscalendar.com"


exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - README.md
  - LICENCE
  - lib/
  - bin/
  - Rakefile

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
