# ----
# Site

title: Tribe Engineering
url: "http://moderntribe.github.io/products-engineering/"
baseurl: "/products-engineering"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Modern Tribe knowledge base for Developers
author:
  name: Modern Tribe
  email:
  twitter: moderntribeinc

# -----
# Build

permalink: pretty

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "The Events Calendar":
    - "https://theeventscalendar.com"


exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - README.md
  - LICENCE
  - lib/
  - bin/
  - Rakefile

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
